#!/usr/bin/env bash

PASSWD=`/home/mdevine/github.com/raku-Hypervisor-VMware-vSphere-REST/example/pstash.raku --stash-path=/home/mdevine/passwd/A028441.khph`
export basepw=$(echo -n "WMATA\\A028441:${PASSWD}" | base64)

#export token=$(curl -k -X POST -H "Authorization: Basic ${basepw}" https://ctvcenterpv.wmata.local/rest/com/vmware/cis/session/ | tr -d '"' | awk -F: '{print $2}' | sed 's/}//')
export token=$(curl -k -X POST -H "Authorization: Basic ${basepw}" https://eqvcsapv.wmata.local/api/session | tr -d '"')

#curl -k -X GET -H "vmware-api-session-id: ${token}" "https://eqvcsapv.wmata.local/api/vcenter/host" -H "Content-Type: application/json" | jq
#  {
#    "host": "host-1024",
#    "name": "eqvpesxi66p.wmata.local",
#    "connection_state": "CONNECTED",
#    "power_state": "POWERED_ON"
#  },

#curl -k -X GET -H "vmware-api-session-id: ${token}" "https://eqvcsapv.wmata.local/api/vcenter/vm" -H "Content-Type: application/json" -d '{ "hosts": "host-1024" }' | jq
curl -k -X GET -H "vmware-api-session-id: ${token}" -H "Content-Type: application/json" 'https://eqvcsapv.wmata.local/api/vcenter/vm?hosts=host-1024' | jq
